[package]
org = "ballerina"
name = "toml"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["toml"]
repository = "https://github.com/ballerina-platform/module-ballerina-toml"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"
