[package]
org = "ballerina"
name = "toml"
version = "0.5.1"
authors = ["Ballerina"]
keywords = ["toml"]
repository = "https://github.com/ballerina-platform/module-ballerina-toml"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"
